export ANTHROPIC_BASE_URL="http://106.53.148.171:38866"
export ANTHROPIC_AUTH_TOKEN=$JW_API_KEY_3
export ANTHROPIC_MODEL="claude-opus-4-8[1m]"
export ANTHROPIC_DEFAULT_OPUS_MODEL="claude-opus-4-8[1m]"
export ANTHROPIC_DEFAULT_SONNET_MODEL="claude-opus-4-8[1m]"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="claude-opus-4-8[1m]"
export CLAUDE_CODE_SUBAGENT_MODEL="claude-opus-4-8[1m]"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
export CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK=1
export CLAUDE_CODE_EFFORT_LEVEL=max

claude --thinking-display summarized "$@"
