version = 1

[envs.fd-find]
channels = ["conda-forge"]
dependencies = { fd-find = "*" }
exposed = { fd = "fd" }

[envs.gawk]
channels = ["conda-forge"]
dependencies = { gawk = "*" }
exposed = { awk = "awk", gawk = "gawk", gawkbug = "gawkbug" }

[envs.hyperfine]
channels = ["conda-forge"]
dependencies = { hyperfine = "*" }
exposed = { hyperfine = "hyperfine" }

[envs.nodejs]
channels = ["conda-forge"]
dependencies = { nodejs = "*" }
exposed = { node = "node", npm = "npm", npx = "npx" }

[envs.fzf]
channels = ["conda-forge"]
dependencies = { fzf = "*" }
exposed = { fzf = "fzf" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.peco]
channels = ["conda-forge"]
dependencies = { peco = "*" }
exposed = { peco = "peco" }

[envs.dust]
channels = ["conda-forge"]
dependencies = { dust = "*" }
exposed = { dust = "dust" }

[envs.gh]
channels = ["conda-forge"]
dependencies = { gh = "*" }
exposed = { gh = "gh" }

[envs.cmake]
channels = ["conda-forge"]
dependencies = { cmake = "*" }
exposed = { ccmake = "ccmake", cmake = "cmake", cpack = "cpack", ctest = "ctest" }

[envs.help2man]
channels = ["conda-forge"]
dependencies = { help2man = "*" }
exposed = { help2man = "help2man" }

[envs.tokei]
channels = ["conda-forge"]
dependencies = { tokei = "*" }
exposed = { tokei = "tokei" }

[envs.git-lfs]
channels = ["conda-forge"]
dependencies = { git-lfs = "*" }
exposed = { git-lfs = "git-lfs" }

[envs.clang-tools]
channels = ["conda-forge"]
dependencies = { clang-tools = "22.*" }
exposed = { amdgpu-arch = "amdgpu-arch", analyze-build = "analyze-build", clang-apply-replacements = "clang-apply-replacements", clang-change-namespace = "clang-change-namespace", clang-check = "clang-check", clang-doc = "clang-doc", clang-extdef-mapping = "clang-extdef-mapping", clang-include-cleaner = "clang-include-cleaner", clang-include-fixer = "clang-include-fixer", clang-installapi = "clang-installapi", clang-linker-wrapper = "clang-linker-wrapper", clang-move = "clang-move", clang-nvlink-wrapper = "clang-nvlink-wrapper", clang-offload-bundler = "clang-offload-bundler", clang-query = "clang-query", clang-refactor = "clang-refactor", clang-reorder-fields = "clang-reorder-fields", clang-repl = "clang-repl", clang-scan-deps = "clang-scan-deps", clang-sycl-linker = "clang-sycl-linker", clang-tidy = "clang-tidy", clangd = "clangd", diagtool = "diagtool", find-all-symbols = "find-all-symbols", git-clang-format = "git-clang-format", hmaptool = "hmaptool", intercept-build = "intercept-build", modularize = "modularize", nvptx-arch = "nvptx-arch", offload-arch = "offload-arch", pp-trace = "pp-trace", run-clang-tidy = "run-clang-tidy", scan-build = "scan-build", scan-build-py = "scan-build-py", scan-view = "scan-view" }

[envs.parallel]
channels = ["conda-forge"]
dependencies = { parallel = "*" }
exposed = { env_parallel = "env_parallel", "env_parallel.ash" = "env_parallel.ash", "env_parallel.dash" = "env_parallel.dash", "env_parallel.mksh" = "env_parallel.mksh", "env_parallel.pdksh" = "env_parallel.pdksh", niceload = "niceload", parallel = "parallel", parcat = "parcat", parset = "parset", parsort = "parsort", sem = "sem", sql = "sql" }

[envs.nvim]
channels = ["conda-forge"]
dependencies = { nvim = "*" }
exposed = { nvim = "nvim" }

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.starship]
channels = ["conda-forge"]
dependencies = { starship = "*" }
exposed = { starship = "starship" }

[envs.lazysql]
channels = ["https://prefix.dev/github-releases"]
dependencies = { lazysql = "*" }
exposed = { lazysql = "lazysql" }

[envs.ruff]
channels = ["conda-forge"]
dependencies = { ruff = "*" }
exposed = { ruff = "ruff" }

[envs.diffnav]
channels = ["conda-forge"]
dependencies = { diffnav = "*" }
exposed = { diffnav = "diffnav" }

[envs.tmux]
channels = ["conda-forge"]
dependencies = { tmux = "3.5.*" }
exposed = { tmux = "tmux" }

[envs.rust]
channels = ["conda-forge"]
dependencies = { rust = "1.*", rust-analyzer = "*" }
exposed = { cargo = "cargo", rustc = "rustc", rustdoc = "rustdoc", rust-gdb = "rust-gdb", rust-lldb = "rust-lldb", rust-analyzer = "rust-analyzer" }

[envs.postgresql]
channels = ["conda-forge"]
dependencies = { postgresql = "18.*" }
exposed = { clusterdb = "clusterdb", createdb = "createdb", createuser = "createuser", dropdb = "dropdb", dropuser = "dropuser", ecpg = "ecpg", initdb = "initdb", oid2name = "oid2name", pg_amcheck = "pg_amcheck", pg_archivecleanup = "pg_archivecleanup", pg_basebackup = "pg_basebackup", pg_checksums = "pg_checksums", pg_combinebackup = "pg_combinebackup", pg_controldata = "pg_controldata", pg_createsubscriber = "pg_createsubscriber", pg_ctl = "pg_ctl", pg_dump = "pg_dump", pg_dumpall = "pg_dumpall", pg_isready = "pg_isready", pg_receivewal = "pg_receivewal", pg_recvlogical = "pg_recvlogical", pg_resetwal = "pg_resetwal", pg_restore = "pg_restore", pg_rewind = "pg_rewind", pg_test_fsync = "pg_test_fsync", pg_test_timing = "pg_test_timing", pg_upgrade = "pg_upgrade", pg_verifybackup = "pg_verifybackup", pg_waldump = "pg_waldump", pg_walsummary = "pg_walsummary", pgbench = "pgbench", postgres = "postgres", psql = "psql", reindexdb = "reindexdb", vacuumdb = "vacuumdb", vacuumlo = "vacuumlo" }

[envs.btop]
channels = ["conda-forge"]
dependencies = { btop = "*" }
exposed = { btop = "btop" }

